name: Manual Run Example

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Which environment to deploy to?'
        required: true
        default: 'staging'

jobs:
  manual-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use secret token in environment variable
        shell: bash
        run: |
          echo "Running deployment to ${{ github.event.inputs.environment }}"
          
          if [ -z "$DEPLOY_SECRET" ]; then
            echo "🚨 Secret is empty or not set"
          else
            echo "✅ Secret is set. Length: ${#DEPLOY_SECRET}"
          fi
        env:
          DEPLOY_SECRET: ${{ secrets.HELLO_WORLD }}
