name: "T"

env:
  OUT_DIR: "${{ github.workspace }}/out"

on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    name: "Build kernel"
    runs-on: ubuntu-24.04
    env:
      WORKSPACE: ${{ github.workspace }}
      KERNEL_DEVICE: ruby
      name: "${{ KERNEL_DEVICE }}-apatch.img"
    steps:
      - name: "Test"
        run: "echo ${{ env.name }}"
